---
netbox_base_dir: /opt/netbox
netbox_port: 8080

netbox_netbox_docker_version: 3.0.1
netbox_netbox_version: 4.1
netbox_netbox_image: "docker.io/netboxcommunity/netbox:v{{ netbox_netbox_version }}-{{ netbox_netbox_docker_version }}"
netbox_valkey_image: docker.io/valkey/valkey:8.0-alpine
netbox_postgres_image: docker.io/postgres:16-alpine
netbox_caddy_image: docker.io/caddy:2-alpine

netbox_path_media: ""
netbox_path_postgres: ""
netbox_path_valkey: ""

netbox_use_caddy: false
netbox_caddy_letsencrypt_email: ""
netbox_caddy_http_port: 80
netbox_caddy_https_port: 443
netbox_ssl_cert_bundle: ""
netbox_ssl_cert_key: ""

netbox_admin_api_token: ""
netbox_admin_email: admin@example.com
netbox_admin_password: admin
netbox_admin_username: admin
netbox_allowed_hosts: "*"
netbox_container_env: []
netbox_container_labels: []
netbox_cors_origin_allow_all: true
netbox_cors_origin_whitelist: http://localhost
netbox_default_page_size: 250
netbox_email_certfile: ""
netbox_email_from: netbox@bar.com
netbox_email_keyfile: ""
netbox_email_password: ""
netbox_email_port: 25
netbox_email_server: localhost
netbox_email_timeout: 5
netbox_email_use_ssl: false
netbox_email_use_tls: false
netbox_email_username: netbox
netbox_enforce_global_unique: false
netbox_graphql_enabled: true
netbox_housekeeping_interval: 86400
netbox_login_required: false
netbox_max_page_size: 1000
netbox_metrics_enabled: false
netbox_pg_db: netbox
netbox_pg_host: postgres
netbox_pg_password: >
  "{{ lookup('ansible.builtin.password', '/tmp/netbox_pg_password.txt', chars=['ascii_letters'], length=16, seed=inventory_hostname+'.netbox_pg_password') }}"
netbox_pg_user: netbox
netbox_additional_network_names: ""
netbox_valkey_cache_host: valkey-cache
netbox_valkey_cache_insecure_skip_tls_verify: false
netbox_valkey_cache_password: >
  "{{ lookup('ansible.builtin.password', '/tmp/netbox_valkey_cache_password.txt', chars=['ascii_letters'], length=16, seed=inventory_hostname+'.netbox_valkey_cache_password') }}"
netbox_valkey_cache_ssl: false
netbox_valkey_host: valkey
netbox_valkey_insecure_skip_tls_verify: false
netbox_valkey_password: >
  "{{ lookup('ansible.builtin.password', '/tmp/netbox_valkey_password.txt', chars=['ascii_letters'], length=16, seed=inventory_hostname+'.netbox_valkey_password') }}"
netbox_secret_key: >
  "{{ lookup('ansible.builtin.password', '/tmp/netbox_secret_key.txt', chars=['ascii_letters'], length=50, seed=inventory_hostname+'.netbox_secret_key') }}"
netbox_skip_startup_scripts: false
netbox_skip_superuser: false
netbox_webhooks_enabled: true
netbox_extra_config: ""
netbox_custom_pipeline_content: ""
